### ISSUE TITLE
Implement mobile menu toggler

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/ember-tabler#13]
Tabler-ui hamburger menu toggles `#headerMenuCollapse`

**Comment by bravo-kernel** [comment]
### TODO:

- close the menu once a nav-item has been selected

**Comment by vadikcorp** [comment]
take it

**Comment by bravo-kernel** [comment]
Awesome, let me push one small change right now.

**Comment by vadikcorp** [comment]
> Awesome, let me push one small change right now.

Okay i`m waiting:)

**Comment by vadikcorp** [comment]
@bravo-kernel okay i`m sorry, but i have trouble with ember, exactly with passing data from child to parent :(, tip for you: on tabler-header.hbs u have ' onClick={{action "toggleNav"}} ' when clicking on hamburger icon, so in child component ' <TableHeaderNav/>' when click on any link you must trigger that action too, smth like trigger event from child to parent, hope it will help u

**Comment by bravo-kernel** [comment]
No problem, I appreciate the attempt. And you are right about the parent/child relationship. Something needs to be reworked there. Thanks for your help!

**Comment by bravo-kernel** [comment]
This is the one thing that is annoying me about the template btw. The fact that header and nav are siblings makes it unneeded complex IMO.

**Comment by bravo-kernel** [comment]
@vadikcorp I have implemented this. The solution was to pass down the closure action `toggleNav` down in this order

 TablerHeader.hbs > TablerHeaderNav.hbs > TablerNavLink and TablerNavDropdownItem

The last two templates contain Bootstrap 4 display conditions so the closure action is only applied when on medium or smaller devices. I am pleased with the result. Would you mind testing before I close?

**Comment by bravo-kernel** [comment]
The actual toggling is [handled in this routte](https://github.com/alt3/ember-tabler/blob/master/addon/components/tabler-header.js#L10).

The closure action is passed down in the templates, in this order:

1. [`TablerHeader`](https://github.com/alt3/ember-tabler/blob/master/addon/templates/components/tabler-header.hbs#L32)
    - [`TablerHeaderNav`](https://github.com/alt3/ember-tabler/blob/master/addon/templates/components/tabler-header-nav.hbs#L25)
        - either [`TablerNavLink`](https://github.com/alt3/ember-tabler/blob/master/addon/templates/components/tabler-nav-link.hbs#L11)
        - or [`TablerNavDropdownItem`](https://github.com/alt3/ember-tabler/blob/master/addon/templates/components/tabler-nav-dropdown-item.hbs#L4)

### Note:

We use [ember-link-action](https://github.com/Kuzirashi/ember-link-action) so we can generate a link-to using the closure action.
