### ISSUE TITLE
Populate the charts

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/ember-tabler#3]
Tabler-ui uses [C3.js](https://c3js.org/), the D3-based reusable chart library so perhaps best to utilize something similar to:

- ~https://github.com/Glavin001/ember-c3~
- https://medium.com/the-backlog-by-ecaresoft/extending-ember-c3-charts-using-base-component-approach-78df1d635050

**Update**
ember-c3 is way too outdated to use and alternatives are either non-free or outdated as well so going with ember-auto-import and most recent versions of c3js seems the way to go.

**Comment by bravo-kernel** [comment]
Seems like ember-c3 is getting an update soon: https://github.com/Glavin001/ember-c3/issues/77 so best to await that. Putting ticket on-hold.

**Comment by maxwondercorn** [comment]
The updated ember-c3 has been released
